export const DEFAULT_CATEGORIES = [
    // Expense categories
    { id: 'cat-food', name: 'Ăn uống', type: 'EXPENSE', icon: 'Utensils', color: '#f97316' },
    { id: 'cat-transport', name: 'Di chuyển & Xe', type: 'EXPENSE', icon: 'Car', color: '#0ea5e9' },
    { id: 'cat-shopping', name: 'Mua sắm', type: 'EXPENSE', icon: 'ShoppingBag', color: '#ec4899' },
    { id: 'cat-bills', name: 'Hóa đơn & Tiện ích', type: 'EXPENSE', icon: 'Receipt', color: '#eab308' },
    { id: 'cat-housing', name: 'Nhà cửa & Thuê nhà', type: 'EXPENSE', icon: 'Home', color: '#8b5cf6' },
    { id: 'cat-entertainment', name: 'Giải trí & Du lịch', type: 'EXPENSE', icon: 'Gamepad2', color: '#10b981' },
    { id: 'cat-health', name: 'Sức khỏe & Y tế', type: 'EXPENSE', icon: 'HeartPulse', color: '#ef4444' },
    { id: 'cat-education', name: 'Giáo dục & Khóa học', type: 'EXPENSE', icon: 'GraduationCap', color: '#06b6d4' },
    { id: 'cat-invest-exp', name: 'Đầu tư & Tích lũy', type: 'EXPENSE', icon: 'TrendingUp', color: '#6366f1' },
    { id: 'cat-other-exp', name: 'Chi phí khác', type: 'EXPENSE', icon: 'MoreHorizontal', color: '#64748b' },
    // Income categories
    { id: 'cat-salary', name: 'Lương chính', type: 'INCOME', icon: 'Briefcase', color: '#10b981' },
    { id: 'cat-bonus', name: 'Thưởng & Làm thêm', type: 'INCOME', icon: 'Gift', color: '#f59e0b' },
    { id: 'cat-invest-inc', name: 'Lợi nhuận đầu tư', type: 'INCOME', icon: 'Coins', color: '#3b82f6' },
    { id: 'cat-business', name: 'Kinh doanh & Bán hàng', type: 'INCOME', icon: 'Store', color: '#8b5cf6' },
    { id: 'cat-other-inc', name: 'Thu nhập khác', type: 'INCOME', icon: 'PlusCircle', color: '#14b8a6' },
];
export const POPULAR_TAGS = [
    'Ăn trưa', 'Cafe', 'Tiệc tùng', 'Gia đình', 'Công tác',
    'Grab/Be', 'Xăng xe', 'Siêu thị', 'Online', 'Du lịch',
    'Sức khỏe', 'Khẩn cấp', 'Đầu tư'
];
export const VIETNAMESE_BANKS = [
    { code: 'VCB', name: 'Vietcombank', color: '#007A33' },
    { code: 'TCB', name: 'Techcombank', color: '#ED1C24' },
    { code: 'MBB', name: 'MB Bank', color: '#0047BA' },
    { code: 'ACB', name: 'ACB Bank', color: '#005CA9' },
    { code: 'VPB', name: 'VPBank', color: '#00A651' },
    { code: 'BIDV', name: 'BIDV', color: '#006738' },
    { code: 'VIB', name: 'VIB', color: '#00539B' },
    { code: 'TPB', name: 'TPBank', color: '#802682' },
    { code: 'MOMO', name: 'Ví MoMo', color: '#A50064' },
    { code: 'ZALOPAY', name: 'ZaloPay', color: '#0068FF' },
];
export const INITIAL_WALLETS = [
    {
        id: 'wal-cash',
        name: 'Tiền mặt ví tay',
        type: 'CASH',
        balance: 2850000,
        initialBalance: 3000000,
        currency: 'VND',
        color: '#10b981',
        icon: 'Banknote',
        createdAt: '2026-01-01',
    },
    {
        id: 'wal-tcb',
        name: 'Techcombank Chi tiêu',
        type: 'BANK',
        balance: 27450000,
        initialBalance: 25000000,
        bankName: 'Techcombank',
        accountNumber: '19038899887766',
        currency: 'VND',
        color: '#ef4444',
        icon: 'CreditCard',
        createdAt: '2026-01-01',
    },
    {
        id: 'wal-vcb',
        name: 'Vietcombank Nhận lương',
        type: 'BANK',
        balance: 38200000,
        initialBalance: 20000000,
        bankName: 'Vietcombank',
        accountNumber: '00110099882211',
        currency: 'VND',
        color: '#007a33',
        icon: 'Building2',
        createdAt: '2026-01-01',
    },
    {
        id: 'wal-credit',
        name: 'VPBank Cashback StepUp',
        type: 'CREDIT',
        balance: 4680000, // Current debt balance
        initialBalance: 0,
        bankName: 'VPBank',
        accountNumber: '•••• 5824',
        creditLimit: 30000000,
        currency: 'VND',
        color: '#8b5cf6',
        icon: 'CreditCard',
        createdAt: '2026-01-01',
    },
    {
        id: 'wal-savings',
        name: 'Sổ tiết kiệm MB Bank 6T',
        type: 'SAVINGS',
        balance: 150000000,
        initialBalance: 150000000,
        bankName: 'MB Bank',
        accountNumber: 'MB-SAV-88992',
        interestRate: 6.2,
        currency: 'VND',
        color: '#3b82f6',
        icon: 'PiggyBank',
        createdAt: '2026-01-01',
    },
];
export const INITIAL_PLANNER = {
    monthlyIncome: 32000000,
    needsPercent: 50, // 16,000,000 VND
    wantsPercent: 25, // 8,000,000 VND
    savingsPercent: 15, // 4,800,000 VND
    emergencyPercent: 10, // 3,200,000 VND
    notes: 'Quy tắc phân bổ 4 quỹ: 50% thiết yếu, 25% hưởng thụ, 15% tích lũy đầu tư, 10% quỹ dự phòng khẩn cấp & rủi ro phát sinh',
};
export const INITIAL_BUDGETS = [
    {
        id: 'bud-food',
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        amount: 5500000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
    {
        id: 'bud-shopping',
        categoryId: 'cat-shopping',
        categoryName: 'Mua sắm',
        amount: 3000000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
    {
        id: 'bud-transport',
        categoryId: 'cat-transport',
        categoryName: 'Di chuyển & Xe',
        amount: 1800000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
    {
        id: 'bud-bills',
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        amount: 2500000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
    {
        id: 'bud-housing',
        categoryId: 'cat-housing',
        categoryName: 'Nhà cửa & Thuê nhà',
        amount: 6000000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
    {
        id: 'bud-entertainment',
        categoryId: 'cat-entertainment',
        categoryName: 'Giải trí & Du lịch',
        amount: 2000000,
        month: '2026-09',
        alertThreshold80: true,
        alertThreshold100: true,
    },
];
export const INITIAL_BILLS = [
    {
        id: 'bill-rent',
        name: 'Tiền thuê căn hộ tháng 9',
        amount: 6000000,
        categoryId: 'cat-housing',
        categoryName: 'Nhà cửa & Thuê nhà',
        walletId: 'wal-vcb',
        dueDay: 5,
        frequency: 'MONTHLY',
        status: 'PAID',
        lastPaidDate: '2026-09-05',
        note: 'Chuyển khoản chủ nhà qua Techcombank',
        reminderDaysBefore: 3,
    },
    {
        id: 'bill-electric',
        name: 'Tiền điện EVN Hà Nội',
        amount: 1150000,
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        walletId: 'wal-tcb',
        dueDay: 12,
        frequency: 'MONTHLY',
        status: 'UNPAID',
        note: 'Mã khách hàng PD08876522',
        reminderDaysBefore: 5,
    },
    {
        id: 'bill-internet',
        name: 'Cáp quang FPT Telecom',
        amount: 275000,
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        walletId: 'wal-tcb',
        dueDay: 15,
        frequency: 'MONTHLY',
        status: 'UNPAID',
        note: 'Gói Super 200Mbps',
        reminderDaysBefore: 3,
    },
    {
        id: 'bill-netflix',
        name: 'Gói xem phim Netflix Premium',
        amount: 260000,
        categoryId: 'cat-entertainment',
        categoryName: 'Giải trí & Du lịch',
        walletId: 'wal-credit',
        dueDay: 20,
        frequency: 'MONTHLY',
        status: 'UNPAID',
        note: 'Thanh toán tự động qua thẻ VPBank',
        reminderDaysBefore: 2,
    },
    {
        id: 'bill-water',
        name: 'Nước sinh hoạt Vinaconex',
        amount: 185000,
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        walletId: 'wal-tcb',
        dueDay: 18,
        frequency: 'MONTHLY',
        status: 'UNPAID',
        note: 'Đóng tiền nước định kỳ',
        reminderDaysBefore: 3,
    },
];
export const INITIAL_GOALS = [
    {
        id: 'goal-bike',
        name: 'Đổi xe máy Honda SH 160i ABS',
        targetAmount: 95000000,
        currentAmount: 68500000,
        deadline: '2026-12-31',
        color: '#0ea5e9',
        icon: 'Bike',
        category: 'Phương tiện',
        history: [
            { id: 'gh-1', date: '2026-07-05', amount: 20000000, type: 'DEPOSIT', note: 'Trích từ thưởng quý' },
            { id: 'gh-2', date: '2026-08-05', amount: 25000000, type: 'DEPOSIT', note: 'Tích lũy tháng 8' },
            { id: 'gh-3', date: '2026-09-02', amount: 23500000, type: 'DEPOSIT', note: 'Tích lũy tháng 9' },
        ],
        createdAt: '2026-07-01',
    },
    {
        id: 'goal-emergency',
        name: 'Quỹ dự phòng khẩn cấp 6 tháng',
        targetAmount: 60000000,
        currentAmount: 60000000,
        deadline: '2026-10-31',
        color: '#10b981',
        icon: 'ShieldCheck',
        category: 'An toàn tài chính',
        history: [
            { id: 'gh-e1', date: '2026-06-15', amount: 30000000, type: 'DEPOSIT', note: 'Khoản tích lũy ban đầu' },
            { id: 'gh-e2', date: '2026-07-20', amount: 15000000, type: 'DEPOSIT', note: 'Nạp thêm từ lương' },
            { id: 'gh-e3', date: '2026-08-25', amount: 15000000, type: 'DEPOSIT', note: 'Hoàn thành 100% mục tiêu!' },
        ],
        createdAt: '2026-06-01',
    },
    {
        id: 'goal-japan',
        name: 'Du lịch Tokyo - Kyoto Nhật Bản',
        targetAmount: 38000000,
        currentAmount: 18500000,
        deadline: '2027-04-15',
        color: '#ec4899',
        icon: 'Plane',
        category: 'Du lịch',
        history: [
            { id: 'gh-j1', date: '2026-08-10', amount: 10000000, type: 'DEPOSIT', note: 'Khởi động quỹ hoa anh đào' },
            { id: 'gh-j2', date: '2026-09-03', amount: 8500000, type: 'DEPOSIT', note: 'Tiết kiệm tháng 9' },
        ],
        createdAt: '2026-08-01',
    },
    {
        id: 'goal-macbook',
        name: 'MacBook Pro M4 cho công việc',
        targetAmount: 45000000,
        currentAmount: 28000000,
        deadline: '2026-11-30',
        color: '#8b5cf6',
        icon: 'Laptop',
        category: 'Thiết bị công nghệ',
        history: [
            { id: 'gh-m1', date: '2026-08-15', amount: 15000000, type: 'DEPOSIT', note: 'Tiết kiệm từ dự án ngoài' },
            { id: 'gh-m2', date: '2026-09-04', amount: 13000000, type: 'DEPOSIT', note: 'Thưởng KPI' },
        ],
        createdAt: '2026-08-15',
    },
];
export const INITIAL_TRANSACTIONS = [
    // September 2026
    {
        id: 'tx-001',
        type: 'INCOME',
        amount: 30000000,
        categoryId: 'cat-salary',
        categoryName: 'Lương chính',
        walletId: 'wal-vcb',
        walletName: 'Vietcombank Nhận lương',
        date: '2026-09-01T09:30:00',
        note: 'Lương tháng 08/2026 từ công ty công nghệ',
        tags: ['Lương'],
        createdAt: '2026-09-01T09:30:00',
    },
    {
        id: 'tx-002',
        type: 'TRANSFER',
        amount: 15000000,
        walletId: 'wal-vcb',
        walletName: 'Vietcombank Nhận lương',
        toWalletId: 'wal-tcb',
        toWalletName: 'Techcombank Chi tiêu',
        fee: 0,
        date: '2026-09-01T10:00:00',
        note: 'Chuyển tiền vào tài khoản chi tiêu sinh hoạt tháng 9',
        tags: ['Nội bộ'],
        createdAt: '2026-09-01T10:00:00',
    },
    {
        id: 'tx-003',
        type: 'EXPENSE',
        amount: 6000000,
        categoryId: 'cat-housing',
        categoryName: 'Nhà cửa & Thuê nhà',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-05T08:15:00',
        note: 'Thanh toán tiền thuê căn hộ tháng 9/2026',
        tags: ['Gia đình', 'Hóa đơn'],
        createdAt: '2026-09-05T08:15:00',
    },
    {
        id: 'tx-004',
        type: 'EXPENSE',
        amount: 3250000, // Pushes Shopping budget over 3,000,000 VND -> 108%
        categoryId: 'cat-shopping',
        categoryName: 'Mua sắm',
        walletId: 'wal-credit',
        walletName: 'VPBank Cashback StepUp',
        date: '2026-09-04T15:45:00',
        note: 'Mua bàn phím cơ Custom và giày thể thao chạy bộ Nike',
        tags: ['Mua sắm', 'Online'],
        createdAt: '2026-09-04T15:45:00',
    },
    {
        id: 'tx-005',
        type: 'EXPENSE',
        amount: 1450000,
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-05T19:30:00',
        note: 'Tiệc buffet tối cuối tuần liên hoan team công ty',
        tags: ['Ăn tối', 'Tiệc tùng'],
        createdAt: '2026-09-05T19:30:00',
    },
    {
        id: 'tx-006',
        type: 'EXPENSE',
        amount: 850000,
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        walletId: 'wal-cash',
        walletName: 'Tiền mặt ví tay',
        date: '2026-09-03T11:45:00',
        note: 'Đi chợ đầu mối mua thực phẩm tươi sống tuần mới',
        tags: ['Gia đình', 'Siêu thị'],
        createdAt: '2026-09-03T11:45:00',
    },
    {
        id: 'tx-007',
        type: 'EXPENSE',
        amount: 1250000,
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-02T18:30:00',
        note: 'Mua sắm đồ dùng nấu ăn và đồ ăn vặt tại WinMart+',
        tags: ['Siêu thị'],
        createdAt: '2026-09-02T18:30:00',
    },
    {
        id: 'tx-008',
        type: 'EXPENSE',
        amount: 1100000, // Total dining = 1450k + 850k + 1250k + 1100k = 4,650,000 / 5,500,000 = 84.5% (>80% ALERT!)
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-06T12:00:00',
        note: 'Cơm trưa và trà sữa Highlands cùng bạn thân',
        tags: ['Ăn trưa', 'Cafe'],
        createdAt: '2026-09-06T12:00:00',
    },
    {
        id: 'tx-009',
        type: 'EXPENSE',
        amount: 450000,
        categoryId: 'cat-transport',
        categoryName: 'Di chuyển & Xe',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-02T08:00:00',
        note: 'Đổ xăng xe máy & nạp tiền thẻ VETC qua trạm',
        tags: ['Xăng xe'],
        createdAt: '2026-09-02T08:00:00',
    },
    {
        id: 'tx-010',
        type: 'EXPENSE',
        amount: 400000,
        categoryId: 'cat-transport',
        categoryName: 'Di chuyển & Xe',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-09-04T09:15:00',
        note: 'GrabCar đi gặp đối tác khách hàng',
        tags: ['Grab/Be', 'Công tác'],
        createdAt: '2026-09-04T09:15:00',
    },
    {
        id: 'tx-011',
        type: 'EXPENSE',
        amount: 900000,
        categoryId: 'cat-entertainment',
        categoryName: 'Giải trí & Du lịch',
        walletId: 'wal-credit',
        walletName: 'VPBank Cashback StepUp',
        date: '2026-09-03T20:30:00',
        note: 'Vé xem phim IMAX và bắp nước tại CGV Vincom',
        tags: ['Giải trí', 'Bạn bè'],
        createdAt: '2026-09-03T20:30:00',
    },
    {
        id: 'tx-012',
        type: 'INCOME',
        amount: 5500000,
        categoryId: 'cat-bonus',
        categoryName: 'Thưởng & Làm thêm',
        walletId: 'wal-vcb',
        walletName: 'Vietcombank Nhận lương',
        date: '2026-09-04T16:00:00',
        note: 'Thù lao thiết kế UI/UX freelance dự án web',
        tags: ['Freelance', 'Thu nhập phụ'],
        createdAt: '2026-09-04T16:00:00',
    },
    // August 2026 (provides multi-month comparison data for analytics)
    {
        id: 'tx-013',
        type: 'INCOME',
        amount: 30000000,
        categoryId: 'cat-salary',
        categoryName: 'Lương chính',
        walletId: 'wal-vcb',
        walletName: 'Vietcombank Nhận lương',
        date: '2026-08-01T09:00:00',
        note: 'Lương tháng 07/2026',
        tags: ['Lương'],
        createdAt: '2026-08-01T09:00:00',
    },
    {
        id: 'tx-014',
        type: 'EXPENSE',
        amount: 6000000,
        categoryId: 'cat-housing',
        categoryName: 'Nhà cửa & Thuê nhà',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-08-05T10:00:00',
        note: 'Tiền thuê căn hộ tháng 8',
        tags: ['Hóa đơn'],
        createdAt: '2026-08-05T10:00:00',
    },
    {
        id: 'tx-015',
        type: 'EXPENSE',
        amount: 4800000,
        categoryId: 'cat-food',
        categoryName: 'Ăn uống',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-08-15T19:00:00',
        note: 'Tổng chi phí ăn uống & chợ tháng 8',
        tags: ['Ăn uống'],
        createdAt: '2026-08-15T19:00:00',
    },
    {
        id: 'tx-016',
        type: 'EXPENSE',
        amount: 2200000,
        categoryId: 'cat-shopping',
        categoryName: 'Mua sắm',
        walletId: 'wal-credit',
        walletName: 'VPBank Cashback StepUp',
        date: '2026-08-18T14:30:00',
        note: 'Quần áo Uniqlo đợt khuyến mãi hè',
        tags: ['Mua sắm'],
        createdAt: '2026-08-18T14:30:00',
    },
    {
        id: 'tx-017',
        type: 'EXPENSE',
        amount: 1450000,
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        walletId: 'wal-tcb',
        walletName: 'Techcombank Chi tiêu',
        date: '2026-08-12T11:00:00',
        note: 'Tiền điện nước và internet tháng 8',
        tags: ['Hóa đơn'],
        createdAt: '2026-08-12T11:00:00',
    },
    {
        id: 'tx-018',
        type: 'INCOME',
        amount: 4000000,
        categoryId: 'cat-invest-inc',
        categoryName: 'Lợi nhuận đầu tư',
        walletId: 'wal-vcb',
        walletName: 'Vietcombank Nhận lương',
        date: '2026-08-20T10:30:00',
        note: 'Cổ tức chứng khoán FPT & HPG',
        tags: ['Đầu tư'],
        createdAt: '2026-08-20T10:30:00',
    },
];
export const DEFAULT_SPENDING_ITEMS = [
    {
        id: 'spend-food',
        categoryId: 'cat-food',
        categoryName: 'Ăn uống & Cà phê',
        icon: 'Utensils',
        color: '#f97316',
        monthlyExpense: 5500000,
        isSelected: true,
        cutPercent: 20,
    },
    {
        id: 'spend-shopping',
        categoryId: 'cat-shopping',
        categoryName: 'Mua sắm & Quần áo',
        icon: 'ShoppingBag',
        color: '#ec4899',
        monthlyExpense: 3000000,
        isSelected: true,
        cutPercent: 30,
    },
    {
        id: 'spend-entertainment',
        categoryId: 'cat-entertainment',
        categoryName: 'Giải trí & Du lịch',
        icon: 'Gamepad2',
        color: '#10b981',
        monthlyExpense: 2000000,
        isSelected: true,
        cutPercent: 25,
    },
    {
        id: 'spend-housing',
        categoryId: 'cat-housing',
        categoryName: 'Nhà cửa & Tiền thuê',
        icon: 'Home',
        color: '#8b5cf6',
        monthlyExpense: 6000000,
        isSelected: false,
        cutPercent: 10,
    },
    {
        id: 'spend-bills',
        categoryId: 'cat-bills',
        categoryName: 'Hóa đơn & Tiện ích',
        icon: 'Receipt',
        color: '#eab308',
        monthlyExpense: 2500000,
        isSelected: false,
        cutPercent: 15,
    },
    {
        id: 'spend-transport',
        categoryId: 'cat-transport',
        categoryName: 'Di chuyển & Xăng xe',
        icon: 'Car',
        color: '#0ea5e9',
        monthlyExpense: 1800000,
        isSelected: false,
        cutPercent: 20,
    },
    {
        id: 'spend-health',
        categoryId: 'cat-health',
        categoryName: 'Sức khỏe & Y tế',
        icon: 'HeartPulse',
        color: '#ef4444',
        monthlyExpense: 1200000,
        isSelected: false,
        cutPercent: 10,
    },
    {
        id: 'spend-education',
        categoryId: 'cat-education',
        categoryName: 'Giáo dục & Khóa học',
        icon: 'GraduationCap',
        color: '#06b6d4',
        monthlyExpense: 1500000,
        isSelected: false,
        cutPercent: 15,
    },
    {
        id: 'spend-other',
        categoryId: 'cat-other-exp',
        categoryName: 'Chi phí phát sinh khác',
        icon: 'MoreHorizontal',
        color: '#64748b',
        monthlyExpense: 800000,
        isSelected: false,
        cutPercent: 20,
    },
];
export const DEFAULT_EXTERNAL_LOANS = [
    {
        id: 'loan-bike',
        name: 'Trả góp xe máy / Vay ngân hàng',
        originalDebt: 24000000,
        monthlyPayment: 2200000,
        annualInterestRate: 9.5,
    },
    {
        id: 'loan-relatives',
        name: 'Vay người thân / bạn bè (không lãi)',
        originalDebt: 10000000,
        monthlyPayment: 1000000,
        annualInterestRate: 0,
    },
];
export const INITIAL_SIMULATOR_CONFIG = {
    spendingCategories: DEFAULT_SPENDING_ITEMS,
    projectionMonths: 12,
    savingsAmount: 1500000,
    savingsInterestRate: 5.5,
    investmentAmount: 1500000,
    investmentRateScenario: 8.5,
    customInvestRate: '8.5',
    hasExternalLoan: true,
    externalLoans: DEFAULT_EXTERNAL_LOANS,
};
